"""
Corruption + representation for the motion prior.

Two responsibilities:
  1. Turn a clean (B, T, 2) position window into the model's feature
     representation [offset, velocity, acceleration] -> (B, T, C).
  2. Inject noise the way the sensor would: corrupt the POSITIONS at a
     self-chosen sigma, then recompute derivatives from the corrupted positions
     so the noise propagates into velocity/acceleration realistically.

sigma is generated by US here (we add the noise, so we know it exactly). This
is what keeps the prior sensor-agnostic: it learns "given sigma, denoise",
across a wide sigma range, never conditioning on sensor identity.

v1 uses white i.i.d. Gaussian. Hooks are left for colored noise + outliers.
"""
from __future__ import annotations
import torch
from .config import Config


def positions_to_features(pos: torch.Tensor, cfg: Config) -> torch.Tensor:
    """(B, T, 2) positions -> (B, T, C) features.

    Offsets are relative to the first frame of the window (origin-relative),
    so absolute scene coordinates never enter the model. Velocity and
    acceleration are finite differences, padded at the front so length is kept.
    """
    B, T, _ = pos.shape
    if cfg.data.normalize_to_offsets:
        pos = pos - pos[:, :1, :]  # origin-relative offsets

    feats = [pos]
    if cfg.data.use_velocity:
        vel = torch.zeros_like(pos)
        vel[:, 1:, :] = pos[:, 1:, :] - pos[:, :-1, :]
        feats.append(vel)
    if cfg.data.use_acceleration:
        # acceleration = second difference of position
        acc = torch.zeros_like(pos)
        acc[:, 2:, :] = pos[:, 2:, :] - 2 * pos[:, 1:-1, :] + pos[:, :-2, :]
        feats.append(acc)
    return torch.cat(feats, dim=-1)


def sample_training_sigma(batch: int, cfg: Config, device) -> torch.Tensor:
    """EDM log-normal sampling of the noise level for each window in the batch.

    Returns (B, 1, 1) so it broadcasts over (B, T, 2) positions.
    Clamped to [sigma_min, sigma_max] so we never train outside the sampled range.
    """
    log_sigma = cfg.edm.p_mean + cfg.edm.p_std * torch.randn(batch, device=device)
    sigma = log_sigma.exp().clamp(cfg.edm.sigma_min, cfg.edm.sigma_max)
    return sigma.view(batch, 1, 1)


def corrupt_positions(pos: torch.Tensor, sigma: torch.Tensor,
                      colored: bool = False, corr_len: int = 3) -> torch.Tensor:
    """Add noise to POSITIONS at the given per-window sigma.

    pos:   (B, T, 2) clean positions
    sigma: (B, 1, 1) noise std in position units (metres)
    colored: if True, low-pass filter the noise to make it temporally correlated
             (closer to real sensor drift). v1 uses white noise (colored=False).
    """
    eps = torch.randn_like(pos)
    if colored:
        # simple moving-average low-pass along time, then renormalize to unit std
        k = corr_len
        pad = k // 2
        eps_p = torch.nn.functional.pad(eps.transpose(1, 2), (pad, pad), mode="replicate")
        eps = torch.nn.functional.avg_pool1d(eps_p, kernel_size=k, stride=1).transpose(1, 2)
        eps = eps / (eps.std(dim=1, keepdim=True) + 1e-6)
    return pos + sigma * eps


def make_training_pair(clean_pos: torch.Tensor, cfg: Config):
    """Full training corruption step.

    Input : clean_pos (B, T, 2)
    Output:
        x_noisy       (B, T, C)            noisy INPUT features [pos,vel,acc]
        clean_pos_off (B, T, n_pos_dims)   clean position offsets (the TARGET)
        sigma         (B, 1, 1)

    We corrupt positions, build noisy features (derivatives recomputed from the
    corrupted positions so noise propagates realistically), and the target is
    the clean position offset only (derivatives are context, not predicted).
    """
    device = clean_pos.device
    sigma = sample_training_sigma(clean_pos.shape[0], cfg, device)
    noisy_pos = corrupt_positions(clean_pos, sigma)
    x_noisy = positions_to_features(noisy_pos, cfg)
    clean_feats = positions_to_features(clean_pos, cfg)
    clean_pos_off = clean_feats[..., :cfg.data.n_pos_dims]
    return x_noisy, clean_pos_off, sigma
